// <auto-generated />
using System;
using System.Collections.Generic;
using Intake.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intake.Infrastructure.Migrations
{
    [DbContext(typeof(IntakeContext))]
    [Migration("20260715163242_MakeSenderPhoneNumberOptional")]
    partial class MakeSenderPhoneNumberOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Common.Infrastructure.Events.StoredDomainEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoredDomainEvents", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Intake.Domain.Orders.OrderBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sender", "Intake.Domain.Orders.OrderBase.Sender#Sender", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SenderName");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("TEXT")
                                .HasColumnName("SenderPhoneNumber");
                        });

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasDiscriminator<string>("OrderType").HasValue("OrderBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Intake.Domain.Orders.IncomingOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.HasDiscriminator().HasValue("Incoming");
                });

            modelBuilder.Entity("Intake.Domain.Orders.OutOfBoundsOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("HouseNumber");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("StreetId");

                    b.HasDiscriminator().HasValue("OutOfBounds");
                });

            modelBuilder.Entity("Intake.Domain.Orders.UnwashedOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Unwashed");
                });

            modelBuilder.Entity("Intake.Domain.Orders.ValidatedOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("HouseNumber");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NeighborhoodId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("NeighborhoodId");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("StreetId");

                    b.Property<Guid>("StreetSectionId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("StreetSectionId");

                    b.HasDiscriminator().HasValue("Validated");
                });

            modelBuilder.Entity("Intake.Domain.Orders.WashedOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("HouseNumber");

                    b.Property<Guid>("NeighborhoodId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("NeighborhoodId");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("StreetId");

                    b.Property<Guid>("StreetSectionId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("StreetSectionId");

                    b.HasDiscriminator().HasValue("Washed");
                });
#pragma warning restore 612, 618
        }
    }
}
