// <auto-generated />
using System;
using System.Collections.Generic;
using Intake.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intake.Infrastructure.Migrations
{
    [DbContext(typeof(IntakeContext))]
    partial class IntakeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Events.StoredDomainEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoredDomainEvents", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Intake.Domain.Orders.OrderBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sender", "Intake.Domain.Orders.OrderBase.Sender#Sender", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SenderName");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SenderPhoneNumber");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("TransactionId IS NOT NULL");

                    b.ToTable("Orders", (string)null);

                    b.HasDiscriminator<string>("OrderType").HasValue("OrderBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Intake.Domain.Orders.IncomingOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.HasDiscriminator().HasValue("Incoming");
                });

            modelBuilder.Entity("Intake.Domain.Orders.OutOfBoundsOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HouseNumber");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StreetId");

                    b.HasDiscriminator().HasValue("OutOfBounds");
                });

            modelBuilder.Entity("Intake.Domain.Orders.SettledOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HouseNumber");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StreetId");

                    b.Property<Guid>("TerritoryId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TerritoryId");

                    b.HasDiscriminator().HasValue("Settled");
                });

            modelBuilder.Entity("Intake.Domain.Orders.TransferredOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HouseNumber");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StreetId");

                    b.Property<Guid>("TerritoryId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TerritoryId");

                    b.HasDiscriminator().HasValue("Transferred");
                });

            modelBuilder.Entity("Intake.Domain.Orders.UnwashedOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Unwashed");
                });

            modelBuilder.Entity("Intake.Domain.Orders.ValidatedOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HouseNumber");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("NeighborhoodId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NeighborhoodId");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StreetId");

                    b.Property<Guid>("StreetSectionId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StreetSectionId");

                    b.HasDiscriminator().HasValue("Validated");
                });

            modelBuilder.Entity("Intake.Domain.Orders.WashedOrder", b =>
                {
                    b.HasBaseType("Intake.Domain.Orders.OrderBase");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HouseNumber");

                    b.Property<Guid>("NeighborhoodId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NeighborhoodId");

                    b.Property<Guid>("StreetId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StreetId");

                    b.Property<Guid>("StreetSectionId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StreetSectionId");

                    b.HasDiscriminator().HasValue("Washed");
                });
#pragma warning restore 612, 618
        }
    }
}
