// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeCampaign.Repository;

#nullable disable

namespace TreeCampaign.Repository.Migrations
{
    [DbContext(typeof(TreeCampaignContext))]
    [Migration("20260516205324_CampaignIdRename")]
    partial class CampaignIdRename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("TreeCampaign.Domain.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.StopBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "TreeCampaign.Domain.Stops.StopBase.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressDisplayName");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLatitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLongitude");
                        });

                    b.HasKey("Id");

                    b.ToTable("Stops", (string)null);

                    b.HasDiscriminator<string>("StopType").HasValue("StopBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TreeCampaign.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.AssignedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.StopBase");

                    b.Property<Guid>("AssignedTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.HasDiscriminator().HasValue("Assigned");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.ReopenableStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.StopBase");

                    b.HasDiscriminator().HasValue("ReopenableStop");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.UnassignedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.StopBase");

                    b.HasDiscriminator().HasValue("Unassigned");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.CollectedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.ReopenableStop");

                    b.Property<Guid>("CollectedByTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.HasDiscriminator().HasValue("Collected");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.UnresolvedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.ReopenableStop");

                    b.Property<Guid>("UnresolvedByTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.Property<string>("UnresolvedReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UnresolvedReason");

                    b.HasDiscriminator().HasValue("Unresolved");
                });
#pragma warning restore 612, 618
        }
    }
}
