// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeCampaign.Infrastructure;

#nullable disable

namespace TreeCampaign.Infrastructure.Migrations
{
    [DbContext(typeof(TreeCampaignContext))]
    [Migration("20260801180323_AddScoutGroupIdToCampaign")]
    partial class AddScoutGroupIdToCampaign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Common.Infrastructure.Events.StoredDomainEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoredDomainEvents", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TreeCampaign.Domain.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScoutGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TerritoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.StopBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "TreeCampaign.Domain.Stops.StopBase.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressDisplayName");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLatitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLongitude");

                            b1.Property<Guid>("StreetSectionId")
                                .HasColumnType("TEXT")
                                .HasColumnName("StreetSectionId");
                        });

                    b.HasKey("Id");

                    b.ToTable("Stops", (string)null);

                    b.HasDiscriminator<string>("StopType").HasValue("StopBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TreeCampaign.Domain.TeamMembers.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoutRelativeName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("TreeCampaign.Domain.Teams.TeamBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("TeamKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);

                    b.HasDiscriminator<string>("TeamKind").HasValue("TeamBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.AssignedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.StopBase");

                    b.Property<Guid>("AssignedTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.HasDiscriminator().HasValue("Assigned");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.DeliveredStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.StopBase");

                    b.Property<Guid>("DeliveredByTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.HasDiscriminator().HasValue("Delivered");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.ReopenableStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.StopBase");

                    b.HasDiscriminator().HasValue("ReopenableStop");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.UnassignedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.StopBase");

                    b.Property<Guid?>("AssignedTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.HasDiscriminator().HasValue("Unassigned");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Teams.TrailerTeam", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Teams.TeamBase");

                    b.Property<bool>("IsTrailerFull")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<byte>("TrailerSize")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Trailer");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Teams.WalkingTeam", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Teams.TeamBase");

                    b.HasDiscriminator().HasValue("Walking");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.CollectedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.ReopenableStop");

                    b.Property<Guid>("CollectedByTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.HasDiscriminator().HasValue("Collected");
                });

            modelBuilder.Entity("TreeCampaign.Domain.Stops.UnresolvedStop", b =>
                {
                    b.HasBaseType("TreeCampaign.Domain.Stops.ReopenableStop");

                    b.Property<Guid>("UnresolvedByTeamId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("AssignedTeamId");

                    b.Property<string>("UnresolvedReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UnresolvedReason");

                    b.HasDiscriminator().HasValue("Unresolved");
                });

            modelBuilder.Entity("TreeCampaign.Domain.TeamMembers.TeamMember", b =>
                {
                    b.HasOne("TreeCampaign.Domain.Teams.TeamBase", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeCampaign.Domain.Teams.TeamBase", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
