<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Territory.Api\Territory.Api.csproj" />
    <ProjectReference Include="..\TreeCampaign.Api\TreeCampaign.Api.csproj" />
  </ItemGroup>
</Project>
