// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeTerritory.Repository;

#nullable disable

namespace TreeTerritory.Repository.Migrations
{
    [DbContext(typeof(TreeTerritoryContext))]
    partial class TreeTerritoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TreeTerritory.Domain.Neighborhoods.Neighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryId");

                    b.ToTable("Neighborhoods", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.StreetSections.StreetSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndHouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NeighborhoodId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartHouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NeighborhoodId");

                    b.ToTable("StreetSections", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.Streets.Street", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Streets", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.Territories.Territory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Territories", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.Neighborhoods.Neighborhood", b =>
                {
                    b.HasOne("TreeTerritory.Domain.Territories.Territory", null)
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeTerritory.Domain.StreetSections.StreetSection", b =>
                {
                    b.HasOne("TreeTerritory.Domain.Neighborhoods.Neighborhood", null)
                        .WithMany("StreetSections")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeTerritory.Domain.Neighborhoods.Neighborhood", b =>
                {
                    b.Navigation("StreetSections");
                });
#pragma warning restore 612, 618
        }
    }
}
