<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intake.Application\Intake.Application.csproj" />
    <ProjectReference Include="..\Intake.Domain\Intake.Domain.csproj" />
    <ProjectReference Include="..\Intake.InfraStructure\Intake.InfraStructure.csproj" />
  </ItemGroup>
</Project>
