// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeTerritory.Infrastructure;

#nullable disable

namespace TreeTerritory.Infrastructure.Migrations
{
    [DbContext(typeof(TreeTerritoryContext))]
    [Migration("20260903123711_TrailerSize")]
    partial class TrailerSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Events.StoredDomainEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoredDomainEvents", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TreeTerritory.Domain.Neighborhoods.Neighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryId");

                    b.ToTable("Neighborhoods", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.StreetSections.StreetSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Direction")
                        .HasColumnType("tinyint");

                    b.Property<string>("EvenEndHouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvenStartHouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("MaxTrailerSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<Guid>("NeighborhoodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OddEndHouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OddStartHouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NeighborhoodId");

                    b.ToTable("StreetSections", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.Streets.Street", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Streets", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.Territories.Territory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultZipCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DefaultZipCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ScoutGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ScoutGroupId");

                    b.HasKey("Id");

                    b.ToTable("Territories", (string)null);
                });

            modelBuilder.Entity("TreeTerritory.Domain.Neighborhoods.Neighborhood", b =>
                {
                    b.HasOne("TreeTerritory.Domain.Territories.Territory", null)
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeTerritory.Domain.StreetSections.StreetSection", b =>
                {
                    b.HasOne("TreeTerritory.Domain.Neighborhoods.Neighborhood", null)
                        .WithMany("StreetSections")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeTerritory.Domain.Neighborhoods.Neighborhood", b =>
                {
                    b.Navigation("StreetSections");
                });
#pragma warning restore 612, 618
        }
    }
}
