<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Infrastructure\Common.Infrastructure.csproj" />
    <ProjectReference Include="..\Intake.Domain\Intake.Domain.csproj" />
    <ProjectReference Include="..\Intake.Infrastructure\Intake.Infrastructure.csproj" />
    <ProjectReference Include="..\TreeTerritory.Infrastructure\TreeTerritory.Infrastructure.csproj" />
    <ProjectReference Include="..\TreeCampaign.Infrastructure\TreeCampaign.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
  </ItemGroup>
</Project>
